# Generated by Django 3.2.15 on 2022-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/default.jpg', upload_to='profile_images'),
        ),
    ]
