# Generated by Django 3.2.15 on 2022-09-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comments_options'),
        ('profiles', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='default.jpg', upload_to='Profile_images/background_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_posts',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='app.posts'),
            preserve_default=False,
        ),
    ]
