# Generated by Django 3.2.15 on 2022-09-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220930_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_posts',
        ),
    ]
