# Generated by Django 3.2.15 on 2022-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_posts_options'),
        ('profiles', '0011_auto_20221024_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='app.Posts'),
        ),
    ]
