# Generated by Django 4.1.3 on 2022-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_posts_options'),
        ('profiles', '0012_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='saved_posts', to='app.posts'),
        ),
    ]
