# Generated by Django 4.1 on 2022-08-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='Posts',
        ),
    ]
