# Generated by Django 4.1 on 2022-08-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_posts_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='like_count',
        ),
    ]
