# Generated by Django 4.1 on 2022-08-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_posts_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
