# Generated by Django 4.1 on 2022-08-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comments_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(upload_to='images/uploads'),
        ),
    ]
