# Generated by Django 3.2.15 on 2022-09-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comments_options_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-id']},
        ),
    ]
