# Generated by Django 4.1.3 on 2022-12-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.AddField(
            model_name='message',
            name='Message_body',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Message'),
        ),
    ]
