# Generated by Django 4.1.3 on 2022-12-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_message_body_message_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Message_body',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
